### PR TITLE
(GH-3) Allow usage of MemcachedCloud (redislabs.com)

### LINKED ISSUE #3: How to - Use Memcached with MemcachedCloud (RedisLabs) that requires user/pass
There is this nice article out there (https://redislabs.com/memcached-appharbor), but I don't know how to give username and password specifically to Cache.CacheSpecificData. How does one do that?

I'd prefer not to pull out Glav.CacheAdapter and go straight to Enyim to get SASL functionality.

Originally reported by @ferventcoder on Bitbucket at https://bitbucket.org/glav/cacheadapter/issues/39/how-to-use-memcached-with-memcachedcloud

### PR DESCRIPTION
**Pull request by gep13**
This PR is based on work that was originally completed by @ferventcoder.

Fixes #3

### CODE REVIEW

**Review by glav — APPROVED** [review]

**Comment by glav** [comment]
Merged. Thanks for this. Will bump the version and repackage

**Comment by gep13** [comment]
Thank you very much!

**Comment by gep13** [comment]
@glav do you have a rough idea on when you would be publishing a new package version?

**Comment by glav** [comment]
Right now - [here](https://www.nuget.org/packages/Glav.CacheAdapter.Core/):-) Sorry for the delay. 

Note: Updated framewoirk version as well

**Comment by gep13** [comment]
No need to apologise! Thank you very much for getting this pushed out! Will take it for a spin.

**Pull request merged**
